# Generated by Django 5.2.10 on 2026-01-31 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKUSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=15, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Internal Stock Keeping Unit - auto-generated format: XXX-XXX-0001 (12 chars)', max_length=20, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Product barcode - optional but must be unique if provided', max_length=100, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost price per unit', max_digits=10)),
                ('least_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock level for reorder')),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('box', 'Box'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can'), ('bag', 'Bag')], default='pcs', max_length=20)),
                ('pack_size', models.IntegerField(default=1, help_text='Number of units in one pack')),
                ('taxable', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_special', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(help_text='Batch/Lot number', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Product expiry date', null=True)),
                ('quantity', models.IntegerField(help_text='Quantity in this batch')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit for this batch', max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Storage location', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='products.product')),
            ],
            options={
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUST', 'Adjustment'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return'), ('DAMAGE', 'Damage/Loss')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Positive for IN, negative for OUT')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this movement', max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, help_text='Invoice no, order id, POS transaction, etc.', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Additional notes or reason')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product')),
                ('stock', models.ForeignKey(blank=True, help_text='Related stock batch (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='products.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='products_pr_is_acti_1cd666_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quantity'], name='products_pr_quantit_d0d05f_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0), ('least_selling_price__gte', 0), ('wholesale_price__gte', 0), ('retail_price__gte', 0)), name='prices_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('pack_size__gt', 0)), name='pack_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'is_active'], name='products_st_product_174acf_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['expiry_date'], name='products_st_expiry__694693_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['batch_no'], name='products_st_batch_n_15bf85_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stock_unit_cost_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'batch_no')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'movement_type'], name='products_st_product_0214a2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='products_st_created_792bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='products_st_product_a806c1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='products_st_movemen_62ae33_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movement_quantity_not_zero'),
        ),
    ]
